# Go to http://localhost:8080/h2-console/ for H2 Console.
# Username is "sa" and No Password is needed
# Use "jdbc:h2:mem:testdb" as JDBC URL when connecting
spring:
  h2:
    console:
      enabled: true